name: Publish Artifacts Workflow

run-name: 'Publish Artifacts -- ${{github.event.workflow_run.head_branch}}'

on:
  workflow_run:
    workflows:
      - Build Workflow
    types:
      - completed


jobs:
  publish-artifacts:
    name: Publish Artifacts
    runs-on: self-hosted
    if: github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'ikmdev'

    env:
      ARTIFACT_REPOSITORY_ID: "maven-snapshots"
      REPOSITORY_NAME: ${{github.repository}}
      BRANCH: "master"
      MAVEN_SETTING: '/home/ec2-user/maven/.m2/settings.xml'

    steps:
      - name: Checkout Forked Code Repository
        uses: actions/checkout@v4
        if:   github.event.workflow_run.event == 'pull_request'
        with:
          repository: ${{github.actor}}/${{github.event.repository.name}}
          ref: ${{github.event.workflow_run.head_branch}}

      - name: Checkout ikmdev Code Repository
        if:   github.event.workflow_run.event != 'pull_request' && github.event.workflow.name == 'Build Workflow'
        uses: actions/checkout@v4

      - name: Deploy To Nexus
        run: |
          mvn deploy \
           --batch-mode \
           -e \
           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
           -PcodeQuality \
           -DskipTests \
           -s ${{env.MAVEN_SETTING}} \
           -DrepositoryId='${{env.ARTIFACT_REPOSITORY_ID}}' \
           -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}}             
